# @package _global_
checkpoint: null

tensorboard: true
auto_cpu_if_no_gpu: true
device: cuda
mixed_precision: false
save: true
eval_freq: 1000
eval_iters: 100

hparams:
  batch_size: 2
  iterations: 10000

k: 16 
overlap_k: 12
batch_k: 5
info: ""
dre_lamb: 0
dre_path: ""

feed_layers: null
train_projector: false

n_samples: 5 
n_dirs: -1
alphas: [1,2,3,6,10, 15]
iterative: False 
image_size: 128
imgproc: resize

