defaults:
  - model: linear
  - loss: contrastive2
  - generator: stylegan2
  - projector: resnet
  - generator2: stylegan2
    optional: true
  - model2: linear
  - hparams: default # change when Hydra 1.1 releases
  - exps: default
  - misc: train_misc
  - size: ${defaults.2.generator}_${defaults.3.projector} # change when Hydra 1.1 releases
  - hydra/job_logging: custom
  - hydra/output: custom2
