# @package _group_
_target_: colat.projectors.ClipProjector
normalize: True
layers: 5
name: #['RN50', 'RN101', 'RN50x4', 'RN50x16', 'RN50x64', 'ViT-B/32', 'ViT-B/16', 'ViT-L/14', 'ViT-L/14@336px']
load_path: ""